version: '3.2'

services:
  opendistro:
    image: amazon/opendistro-for-elasticsearch:latest
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9601:9600"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
    networks:
      - elk

  logstash:
   image: docker.elastic.co/logstash/logstash-oss:7.12.0
   command: bin/logstash --config.reload.automatic
   volumes:
      - type: bind
        source: ./config/logstash/pipelines.yml
        target: /usr/share/logstash/config/pipelines.yml
        read_only: true
      - type: bind
        source: ./config/logstash/borme_ingestion
        target: /usr/share/logstash/pipelines/borme_ingestion
        bind:
          propagation: shared
        read_only: true
   ports:
      - "5000:5000"
      - "8888:8888"
   expose:
      - "8888"
   environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
   networks:
      - elk
   depends_on:
      - opendistro

  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:latest
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: https://opendistro:9200
      ELASTICSEARCH_HOSTS: https://opendistro:9200
    volumes:
      - type: bind
        source: ./config/kibana/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    networks:
      - elk

  grafana:
    image: grafana/grafana:latest
    expose:
      - "3000"
    environment:
      GF_INSTALL_PLUGINS: marcusolsson-dynamictext-panel
    volumes:
      - type: bind
        source: ./config/grafana/grafana.db
        target: /var/lib/grafana/grafana.db
    ports:
      - 3000:3000
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
