general:
  check_every_s: 20
output_http:
  port: 8888
  server: 127.0.0.1
zones:
  "A CORU\xD1A":
    last_checked: '2020-11-24'
  MADRID:
    last_checked: '2020-09-02'
  PONTEVEDRA:
    last_checked: '2020-11-19'
