# This file is where you define your pipelines. You can define multiple.
# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: borme_ingestion
  path.config: "/usr/share/logstash/pipelines/borme_ingestion/borme_ingestion.conf"
- pipeline.id: borme_empresas
  path.config: "/usr/share/logstash/pipelines/borme_ingestion/borme_empresas.conf"