general:
  check_every_s: 60
output_http:
  port: 8888
  server: logstash
zones:
  "A CORU\xD1A":
    last_checked: '2020-01-01'
  MURCIA:
    last_checked: '2020-01-01'
  PONTEVEDRA:
    last_checked: '2020-01-01'
