general:
  check_every_s: 60
output_http:
  port: 8888
  server: logstash
zones:
  "A CORU\xD1A":
    last_checked: '2021-04-23'
  MADRID:
    last_checked: '2021-04-23'
  PONTEVEDRA:
    last_checked: '2021-04-23'
